"""Catalogo curado de guias oficiales de Quarkus con foco en programacion reactiva.

Cada entrada: nombre del fichero .adoc en quarkusio/quarkus (docs/src/main/asciidoc/)
sin extension. El orden dentro de cada categoria es el orden de lectura sugerido.
"""

CATEGORIAS = [
    ("01-fundamentos", "Fundamentos del modelo reactivo", [
        "quarkus-reactive-architecture",
        "getting-started-reactive",
        "mutiny-primer",
        "vertx",
        "vertx-reference",
        "reactive-event-bus",
        "duplicated-context",
        "context-propagation",
        "virtual-threads",
        "signals",
        "cdi",
        "cdi-reference",
        "lifecycle",
        "config-reference",
    ]),
    ("02-web-http", "HTTP, REST reactivo y WebSockets", [
        "rest",
        "rest-json",
        "rest-client",
        "rest-virtual-threads",
        "rest-data-panache",
        "rest-migration",
        "reactive-routes",
        "http-reference",
        "websockets-next-tutorial",
        "websockets-next-reference",
        "websockets",
        "resteasy",
        "resteasy-client",
        "resteasy-client-multipart",
        "smallrye-graphql",
        "smallrye-graphql-client",
        "qute",
        "qute-reference",
        "security-cors",
        "validation",
        "openapi-swaggerui",
    ]),
    ("03-datos", "Acceso a datos no bloqueante", [
        "reactive-sql-clients",
        "hibernate-reactive",
        "hibernate-reactive-panache",
        "datasource",
        "transaction",
        "mongodb",
        "mongodb-panache",
        "mongodb-dev-services",
        "redis",
        "redis-reference",
        "redis-dev-services",
        "cache",
        "cache-redis-reference",
        "cache-infinispan-reference",
        "infinispan-client",
        "infinispan-client-reference",
        "cassandra",
        "elasticsearch",
        "databases-dev-services",
        "flyway",
        "liquibase",
    ]),
    ("04-mensajeria", "Mensajeria reactiva y streaming", [
        "messaging",
        "messaging-virtual-threads",
        "kafka-getting-started",
        "kafka",
        "kafka-streams",
        "kafka-dev-services",
        "kafka-dev-ui",
        "kafka-schema-registry-avro",
        "kafka-schema-registry-json-schema",
        "amqp",
        "amqp-reference",
        "amqp-dev-services",
        "rabbitmq",
        "rabbitmq-reference",
        "rabbitmq-dev-services",
        "pulsar-getting-started",
        "pulsar",
        "pulsar-dev-services",
        "jms",
        "mailer",
        "mailer-reference",
    ]),
    ("05-grpc", "gRPC reactivo", [
        "grpc",
        "grpc-getting-started",
        "grpc-service-implementation",
        "grpc-service-consumption",
        "grpc-reference",
        "grpc-generation-reference",
        "grpc-virtual-threads",
        "grpc-kubernetes",
        "grpc-xds",
        "grpc-cli",
    ]),
    ("06-resiliencia", "Resiliencia, service discovery y scheduling", [
        "smallrye-fault-tolerance",
        "stork",
        "stork-reference",
        "stork-registration",
        "stork-manual-service-registration",
        "stork-kubernetes",
        "load-shedding-reference",
        "smallrye-health",
        "scheduler",
        "scheduler-reference",
        "quartz",
        "lra",
        "lra-dev-services",
        "software-transactional-memory",
    ]),
    ("07-observabilidad", "Observabilidad de aplicaciones reactivas", [
        "observability",
        "opentelemetry",
        "opentelemetry-tracing",
        "opentelemetry-metrics",
        "opentelemetry-logging",
        "telemetry-micrometer",
        "telemetry-micrometer-tutorial",
        "telemetry-micrometer-to-opentelemetry",
        "logging",
        "centralized-log-management",
        "observability-devservices",
        "observability-devservices-lgtm",
        "jfr",
    ]),
    ("08-rendimiento-nativo", "Rendimiento, nativo y despliegue", [
        "performance-measure",
        "native-reference",
        "building-native-image",
        "writing-native-applications-tips",
        "class-loading-reference",
        "container-image",
        "deploying-to-kubernetes",
        "management-interface-reference",
        "tls-registry-reference",
    ]),
    ("09-testing", "Testing de codigo reactivo", [
        "getting-started-testing",
        "continuous-testing",
        "testing-components",
        "tests-with-coverage",
        "dev-services",
        "getting-started-dev-services",
        "dev-ui",
    ]),
    ("10-extras", "Puntos de entrada y utilidades", [
        "getting-started",
        "cli-tooling",
        "maven-tooling",
        "gradle-tooling",
        "config",
        "config-mappings",
        "config-yaml",
        "update-quarkus",
        "extension-maturity-matrix",
        "all-config",
    ]),
]

# Mapa nombre -> (categoria, titulo de categoria)
def mapa_docs():
    m = {}
    for slug, titulo, docs in CATEGORIAS:
        for d in docs:
            m[d] = slug
    return m
